### ISSUE TITLE
How do I use this program，please？

### ISSUE THREAD

**Issue by bright-men** [djm87/CP-Fit#1]
How do I use this program？

for example：
What programs do I need to use？

 which parameters do i need to change？

 which input file do i need？

**Comment by mjaykr** [comment]
May you please share a small guide for these codes?

**Comment by vicLzs** [comment]
Hi, can you share the code of epsc? Programs included in this project appear to be inoperable

**Comment by djm87** [comment]
This code was built on Matlab and uses it's parallel and optimization toolbox. There are included binaries for linux (I think RHEL) and for windows that allow you to test the Matlab code. For the EPSC case you would need a significant cluster to test. VPSC you could test on a good desktop.  I'm not at liberty to share the source of the CP codes. Also the spherical harmonic texture comparison source is not available. For texture I'd suggest writing your own objective function or look into MTEX to do reconstruction to compare ODF similarity or compare interpolated pole figures made from your model.

You can find details of the code along with examples provided at: https://doi.org/10.1016/j.cma.2021.113747 

How I imagine someone utilizing this repository is: 1) use their own CP or other type of code. 2) From a GA example look at the main.m function which has a function call sequence to explore the dependences etc... 3) look at the bash or other slurm scripts to see how distributed compute was done. 

We put a fair bit of time into the repo and the examples should run fine, but don't expect a highly polished program that works off the shelve. You'll need to spend an hour or two to setup your own data and confirm objectives, etc.. are setup correctly.
